repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        args: [--check]
        
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        args: [--check-only]
        
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        language: system
        types: [python]
        
      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: poetry run python -c "import sys; [print(f.strip()) for f in sys.stdin]"
        language: system
        types: [text]